version: "3"

services:
  backend:
    build: backend/
    container_name: backend
    ports:
      - "3001:3001"
    volumes:
      - static_value:/app/static/
      - media_volume:/app/files/
    restart: always

  frontend:
    build: frontend/
    container_name: frontend
    ports:
      - "3000:3000"
    volumes:
      - static_value:/app/static/
      - media_volume:/app/files/
    restart: always

  nginx:
    image: nginx:1.19.3
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
#      - ./certbot/www:/var/www/certbot/:ro
#      - ./certbot/conf/:/etc/nginx/ssl/:ro
      - static_value:/app/static/
      - media_volume:/app/files/
    depends_on:
      - backend
      - frontend

#  certbot:
#    image: certbot/cerbot:latest
#    volumes:
#      - ./certbot/www/:/var/www/certbot/:rw
#      - ./certbot/conf/:/etc/letsencrypt/:rw

  cron:
   build: add_new_month/
   container_name: cron
   ports:
     - "9000:9000"
   restart: always

volumes:
  static_value:
  media_volume: