# Generated by Django 4.2.6 on 2023-11-18 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(upload_to='about/')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('work_time', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='EmailMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Interior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(upload_to='')),
                ('price', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('is_promo', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(choices=[('January', 'Январь'), ('February', 'Февраль'), ('March', 'Март'), ('April', 'Апрель'), ('May', 'Май'), ('June', 'Июнь'), ('July', 'Июль'), ('August', 'Август'), ('September', 'Сентябрь'), ('October', 'Октябрь'), ('November', 'Ноябрь'), ('December', 'Декабрь')], default='January', max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='SendEmailSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=255)),
                ('port', models.CharField(max_length=255)),
                ('email_address_from', models.CharField(max_length=255)),
                ('email_password', models.CharField(max_length=255)),
                ('email_address_to', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Email settings',
            },
        ),
        migrations.CreateModel(
            name='WorkDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_vacation', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='WorkTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friday', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='friday', to='administration.workday')),
                ('monday', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='monday', to='administration.workday')),
                ('saturday', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='saturday', to='administration.workday')),
                ('sunday', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sunday', to='administration.workday')),
                ('thursday', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='thursday', to='administration.workday')),
                ('tuesday', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tuesday', to='administration.workday')),
                ('wednesday', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wednesday', to='administration.workday')),
            ],
        ),
        migrations.CreateModel(
            name='InteriorImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(upload_to='interior/')),
                ('description', models.TextField()),
                ('interior', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='administration.interior')),
            ],
        ),
        migrations.CreateModel(
            name='Days',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.CharField(choices=[('Monday', 'Понедельник'), ('Tuesday', 'Вторник'), ('Wednesday', 'Среда'), ('Thursday', 'Четверг'), ('Friday', 'Пятница'), ('Saturday', 'Суббота'), ('Sunday', 'Воскресенье')], default='Monday', max_length=9)),
                ('12:00', models.BooleanField()),
                ('12:30', models.BooleanField()),
                ('13:00', models.BooleanField()),
                ('13:30', models.BooleanField()),
                ('14:00', models.BooleanField()),
                ('14:30', models.BooleanField()),
                ('15:00', models.BooleanField()),
                ('15:30', models.BooleanField()),
                ('16:00', models.BooleanField()),
                ('16:30', models.BooleanField()),
                ('17:00', models.BooleanField()),
                ('17:30', models.BooleanField()),
                ('18:00', models.BooleanField()),
                ('18:30', models.BooleanField()),
                ('19:00', models.BooleanField()),
                ('19:30', models.BooleanField()),
                ('20:00', models.BooleanField()),
                ('20:30', models.BooleanField()),
                ('21:00', models.BooleanField()),
                ('21:30', models.BooleanField()),
                ('22:00', models.BooleanField()),
                ('22:30', models.BooleanField()),
                ('23:00', models.BooleanField()),
                ('23:30', models.BooleanField()),
                ('month', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='administration.reservation')),
            ],
        ),
    ]
