# Generated by Django 4.2.6 on 2023-12-14 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name_plural': 'О нас'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name_plural': 'Контакты'},
        ),
        migrations.AlterModelOptions(
            name='interior',
            options={'verbose_name_plural': 'Интерьер'},
        ),
        migrations.AlterModelOptions(
            name='menu',
            options={'verbose_name_plural': 'Меню'},
        ),
        migrations.AlterModelOptions(
            name='menupdf',
            options={'verbose_name_plural': 'Меню в pdf'},
        ),
        migrations.AlterModelOptions(
            name='reservation',
            options={'verbose_name_plural': 'Бронирование'},
        ),
        migrations.AlterModelOptions(
            name='sendemailsettings',
            options={'verbose_name_plural': 'Настройки эл. почты'},
        ),
        migrations.AlterModelOptions(
            name='worktime',
            options={'verbose_name_plural': 'Рабочие часы'},
        ),
        migrations.AddField(
            model_name='menu',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='administration.categorysection'),
        ),
    ]
