# Generated by Django 4.2.6 on 2023-11-01 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interior',
            name='photo',
        ),
        migrations.CreateModel(
            name='InteriorImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(upload_to='interior/')),
                ('interior', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='administration.interior')),
            ],
        ),
    ]
