# Generated by Django 4.2.6 on 2023-11-20 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_days_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='days',
            name='days',
        ),
    ]
