# Generated by Django 4.2.6 on 2023-11-01 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_remove_interior_photo_interiorimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='photo',
            field=models.FileField(upload_to='about/'),
        ),
    ]
