# Generated by Django 4.2.6 on 2024-02-28 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_mainpage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mainpage',
            options={'verbose_name_plural': 'Главная страница'},
        ),
        migrations.AddField(
            model_name='about',
            name='inscription',
            field=models.TextField(default=None, verbose_name='Подпись'),
        ),
        migrations.AlterField(
            model_name='about',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='about',
            name='photo',
            field=models.FileField(upload_to='about/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='title',
            field=models.TextField(verbose_name='Заголовок'),
        ),
    ]
