# Generated by Django 4.2.6 on 2024-02-28 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0004_alter_mainpage_options_about_inscription_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhyUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description1', models.TextField(verbose_name='Описание 1')),
                ('description2', models.TextField(verbose_name='Описание 2')),
                ('description3', models.TextField(verbose_name='Описание 3')),
                ('description4', models.TextField(verbose_name='Описание 4')),
            ],
            options={
                'verbose_name_plural': 'Почему мы',
            },
        ),
    ]
