# Generated by Django 4.2.6 on 2024-02-28 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0005_whyus'),
    ]

    operations = [
        migrations.AddField(
            model_name='interior',
            name='title',
            field=models.TextField(default=None, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='interior',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='interiorimage',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='interiorimage',
            name='photo',
            field=models.FileField(upload_to='interior/', verbose_name='Фото'),
        ),
    ]
