# Generated by Django 4.2.6 on 2024-02-28 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0006_interior_title_alter_interior_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='worktime',
            name='photo',
            field=models.FileField(default=None, upload_to='work_time/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='workday',
            name='end_time',
            field=models.TimeField(default=None),
        ),
        migrations.AlterField(
            model_name='workday',
            name='start_time',
            field=models.TimeField(default=None),
        ),
        migrations.AlterField(
            model_name='worktime',
            name='friday',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='friday', to='administration.workday', verbose_name='Пятница'),
        ),
        migrations.AlterField(
            model_name='worktime',
            name='monday',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='monday', to='administration.workday', verbose_name='Понедельник'),
        ),
        migrations.AlterField(
            model_name='worktime',
            name='saturday',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='saturday', to='administration.workday', verbose_name='Суббота'),
        ),
        migrations.AlterField(
            model_name='worktime',
            name='sunday',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sunday', to='administration.workday', verbose_name='Воскресенье'),
        ),
        migrations.AlterField(
            model_name='worktime',
            name='thursday',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='thursday', to='administration.workday', verbose_name='Четверг'),
        ),
        migrations.AlterField(
            model_name='worktime',
            name='tuesday',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tuesday', to='administration.workday', verbose_name='Вторник'),
        ),
        migrations.AlterField(
            model_name='worktime',
            name='wednesday',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wednesday', to='administration.workday', verbose_name='Среда'),
        ),
    ]
