# Generated by Django 4.2.6 on 2024-03-01 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0007_worktime_photo_alter_workday_end_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationTexts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default=None, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('inscription', models.TextField(default=None, verbose_name='Подпись')),
            ],
            options={
                'verbose_name_plural': 'Текст на странице бронирования',
            },
        ),
    ]
