# Generated by Django 4.2.6 on 2024-03-01 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0008_reservationtexts'),
    ]

    operations = [
        migrations.AddField(
            model_name='worktime',
            name='test',
            field=models.TextField(default=None),
        ),
    ]
