# Generated by Django 4.2.6 on 2024-03-02 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0010_remove_worktime_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('time', models.CharField(max_length=15, verbose_name='Время')),
                ('guests_quantity', models.IntegerField(blank=True, null=True, verbose_name='Количество гостей')),
                ('name', models.CharField(blank=True, max_length=400, null=True, verbose_name='Имя')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер телефона')),
            ],
        ),
        migrations.RemoveField(
            model_name='daycontent',
            name='12:00_guests_quantity',
        ),
        migrations.RemoveField(
            model_name='daycontent',
            name='12:00_name',
        ),
        migrations.RemoveField(
            model_name='daycontent',
            name='12:00_phone_number',
        ),
        migrations.RemoveField(
            model_name='daycontent',
            name='12:30_guests_quantity',
        ),
        migrations.RemoveField(
            model_name='daycontent',
            name='12:30_name',
        ),
        migrations.RemoveField(
            model_name='daycontent',
            name='12:30_phone_number',
        ),
        migrations.RemoveField(
            model_name='daycontent',
            name='13:00_guests_quantity',
        ),
        migrations.RemoveField(
            model_name='daycontent',
            name='13:00_name',
        ),
        migrations.RemoveField(
            model_name='daycontent',
            name='13:00_phone_number',
        ),
        migrations.RemoveField(
            model_name='daycontent',
            name='13:30_guests_quantity',
        ),
        migrations.RemoveField(
            model_name='daycontent',
            name='13:30_name',
        ),
        migrations.RemoveField(
            model_name='daycontent',
            name='13:30_phone_number',
        ),
        migrations.RemoveField(
            model_name='daycontent',
            name='14:00_guests_quantity',
        ),
        migrations.RemoveField(
            model_name='daycontent',
            name='14:00_name',
        ),
        migrations.RemoveField(
            model_name='daycontent',
            name='14:00_phone_number',
        ),
        migrations.RemoveField(
            model_name='daycontent',
            name='14:30_guests_quantity',
        ),
        migrations.RemoveField(
            model_name='daycontent',
            name='14:30_name',
        ),
        migrations.RemoveField(
            model_name='daycontent',
            name='14:30_phone_number',
        ),
        migrations.RemoveField(
            model_name='daycontent',
            name='15:00_guests_quantity',
        ),
        migrations.RemoveField(
            model_name='daycontent',
            name='15:00_name',
        ),
        migrations.RemoveField(
            model_name='daycontent',
            name='15:00_phone_number',
        ),
        migrations.RemoveField(
            model_name='daycontent',
            name='15:30_guests_quantity',
        ),
        migrations.RemoveField(
            model_name='daycontent',
            name='15:30_name',
        ),
        migrations.RemoveField(
            model_name='daycontent',
            name='15:30_phone_number',
        ),
        migrations.RemoveField(
            model_name='daycontent',
            name='16:00_guests_quantity',
        ),
        migrations.RemoveField(
            model_name='daycontent',
            name='16:00_name',
        ),
        migrations.RemoveField(
            model_name='daycontent',
            name='16:00_phone_number',
        ),
        migrations.RemoveField(
            model_name='daycontent',
            name='16:30_guests_quantity',
        ),
        migrations.RemoveField(
            model_name='daycontent',
            name='16:30_name',
        ),
        migrations.RemoveField(
            model_name='daycontent',
            name='16:30_phone_number',
        ),
        migrations.RemoveField(
            model_name='daycontent',
            name='17:00_guests_quantity',
        ),
        migrations.RemoveField(
            model_name='daycontent',
            name='17:00_name',
        ),
        migrations.RemoveField(
            model_name='daycontent',
            name='17:00_phone_number',
        ),
        migrations.RemoveField(
            model_name='daycontent',
            name='17:30_guests_quantity',
        ),
        migrations.RemoveField(
            model_name='daycontent',
            name='17:30_name',
        ),
        migrations.RemoveField(
            model_name='daycontent',
            name='17:30_phone_number',
        ),
        migrations.RemoveField(
            model_name='daycontent',
            name='18:00_guests_quantity',
        ),
        migrations.RemoveField(
            model_name='daycontent',
            name='18:00_name',
        ),
        migrations.RemoveField(
            model_name='daycontent',
            name='18:00_phone_number',
        ),
        migrations.RemoveField(
            model_name='daycontent',
            name='18:30_guests_quantity',
        ),
        migrations.RemoveField(
            model_name='daycontent',
            name='18:30_name',
        ),
        migrations.RemoveField(
            model_name='daycontent',
            name='18:30_phone_number',
        ),
        migrations.RemoveField(
            model_name='daycontent',
            name='19:00_guests_quantity',
        ),
        migrations.RemoveField(
            model_name='daycontent',
            name='19:00_name',
        ),
        migrations.RemoveField(
            model_name='daycontent',
            name='19:00_phone_number',
        ),
        migrations.RemoveField(
            model_name='daycontent',
            name='19:30_guests_quantity',
        ),
        migrations.RemoveField(
            model_name='daycontent',
            name='19:30_name',
        ),
        migrations.RemoveField(
            model_name='daycontent',
            name='19:30_phone_number',
        ),
        migrations.RemoveField(
            model_name='daycontent',
            name='20:00_guests_quantity',
        ),
        migrations.RemoveField(
            model_name='daycontent',
            name='20:00_name',
        ),
        migrations.RemoveField(
            model_name='daycontent',
            name='20:00_phone_number',
        ),
        migrations.RemoveField(
            model_name='daycontent',
            name='20:30_guests_quantity',
        ),
        migrations.RemoveField(
            model_name='daycontent',
            name='20:30_name',
        ),
        migrations.RemoveField(
            model_name='daycontent',
            name='20:30_phone_number',
        ),
        migrations.RemoveField(
            model_name='daycontent',
            name='21:00_guests_quantity',
        ),
        migrations.RemoveField(
            model_name='daycontent',
            name='21:00_name',
        ),
        migrations.RemoveField(
            model_name='daycontent',
            name='21:00_phone_number',
        ),
        migrations.RemoveField(
            model_name='daycontent',
            name='21:30_guests_quantity',
        ),
        migrations.RemoveField(
            model_name='daycontent',
            name='21:30_name',
        ),
        migrations.RemoveField(
            model_name='daycontent',
            name='21:30_phone_number',
        ),
        migrations.RemoveField(
            model_name='daycontent',
            name='22:00_guests_quantity',
        ),
        migrations.RemoveField(
            model_name='daycontent',
            name='22:00_name',
        ),
        migrations.RemoveField(
            model_name='daycontent',
            name='22:00_phone_number',
        ),
        migrations.RemoveField(
            model_name='daycontent',
            name='22:30_guests_quantity',
        ),
        migrations.RemoveField(
            model_name='daycontent',
            name='22:30_name',
        ),
        migrations.RemoveField(
            model_name='daycontent',
            name='22:30_phone_number',
        ),
        migrations.RemoveField(
            model_name='daycontent',
            name='23:00_guests_quantity',
        ),
        migrations.RemoveField(
            model_name='daycontent',
            name='23:00_name',
        ),
        migrations.RemoveField(
            model_name='daycontent',
            name='23:00_phone_number',
        ),
        migrations.RemoveField(
            model_name='daycontent',
            name='23:30_guests_quantity',
        ),
        migrations.RemoveField(
            model_name='daycontent',
            name='23:30_name',
        ),
        migrations.RemoveField(
            model_name='daycontent',
            name='23:30_phone_number',
        ),
        migrations.AddField(
            model_name='daycontent',
            name='12:00_available_seats',
            field=models.IntegerField(default=25, verbose_name='Свободные места'),
        ),
        migrations.AddField(
            model_name='daycontent',
            name='12:30_available_seats',
            field=models.IntegerField(default=25, verbose_name='Свободные места'),
        ),
        migrations.AddField(
            model_name='daycontent',
            name='13:00_available_seats',
            field=models.IntegerField(default=25, verbose_name='Свободные места'),
        ),
        migrations.AddField(
            model_name='daycontent',
            name='13:30_available_seats',
            field=models.IntegerField(default=25, verbose_name='Свободные места'),
        ),
        migrations.AddField(
            model_name='daycontent',
            name='14:00_available_seats',
            field=models.IntegerField(default=25, verbose_name='Свободные места'),
        ),
        migrations.AddField(
            model_name='daycontent',
            name='14:30_available_seats',
            field=models.IntegerField(default=25, verbose_name='Свободные места'),
        ),
        migrations.AddField(
            model_name='daycontent',
            name='15:00_available_seats',
            field=models.IntegerField(default=25, verbose_name='Свободные места'),
        ),
        migrations.AddField(
            model_name='daycontent',
            name='15:30_available_seats',
            field=models.IntegerField(default=25, verbose_name='Свободные места'),
        ),
        migrations.AddField(
            model_name='daycontent',
            name='16:00_available_seats',
            field=models.IntegerField(default=25, verbose_name='Свободные места'),
        ),
        migrations.AddField(
            model_name='daycontent',
            name='16:30_available_seats',
            field=models.IntegerField(default=25, verbose_name='Свободные места'),
        ),
        migrations.AddField(
            model_name='daycontent',
            name='17:00_available_seats',
            field=models.IntegerField(default=25, verbose_name='Свободные места'),
        ),
        migrations.AddField(
            model_name='daycontent',
            name='17:30_available_seats',
            field=models.IntegerField(default=25, verbose_name='Свободные места'),
        ),
        migrations.AddField(
            model_name='daycontent',
            name='18:00_available_seats',
            field=models.IntegerField(default=25, verbose_name='Свободные места'),
        ),
        migrations.AddField(
            model_name='daycontent',
            name='18:30_available_seats',
            field=models.IntegerField(default=25, verbose_name='Свободные места'),
        ),
        migrations.AddField(
            model_name='daycontent',
            name='19:00_available_seats',
            field=models.IntegerField(default=25, verbose_name='Свободные места'),
        ),
        migrations.AddField(
            model_name='daycontent',
            name='19:30_available_seats',
            field=models.IntegerField(default=25, verbose_name='Свободные места'),
        ),
        migrations.AddField(
            model_name='daycontent',
            name='20:00_available_seats',
            field=models.IntegerField(default=25, verbose_name='Свободные места'),
        ),
        migrations.AddField(
            model_name='daycontent',
            name='20:30_available_seats',
            field=models.IntegerField(default=25, verbose_name='Свободные места'),
        ),
        migrations.AddField(
            model_name='daycontent',
            name='21:00_available_seats',
            field=models.IntegerField(default=25, verbose_name='Свободные места'),
        ),
        migrations.AddField(
            model_name='daycontent',
            name='21:30_available_seats',
            field=models.IntegerField(default=25, verbose_name='Свободные места'),
        ),
        migrations.AddField(
            model_name='daycontent',
            name='22:00_available_seats',
            field=models.IntegerField(default=25, verbose_name='Свободные места'),
        ),
        migrations.AddField(
            model_name='daycontent',
            name='22:30_available_seats',
            field=models.IntegerField(default=25, verbose_name='Свободные места'),
        ),
        migrations.AddField(
            model_name='daycontent',
            name='23:00_available_seats',
            field=models.IntegerField(default=25, verbose_name='Свободные места'),
        ),
        migrations.AddField(
            model_name='daycontent',
            name='23:30_available_seats',
            field=models.IntegerField(default=25, verbose_name='Свободные места'),
        ),
        migrations.AddField(
            model_name='days',
            name='all_day_is_reserved',
            field=models.BooleanField(default=False, verbose_name='Весь день Забронирован'),
        ),
        migrations.AlterField(
            model_name='categorysection',
            name='category',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='address',
            field=models.TextField(verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(max_length=255, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='work_time',
            field=models.CharField(max_length=255, verbose_name='Рабочие часы'),
        ),
        migrations.AlterField(
            model_name='daycontent',
            name='12:00',
            field=models.BooleanField(verbose_name='Все места заняты'),
        ),
        migrations.AlterField(
            model_name='daycontent',
            name='12:30',
            field=models.BooleanField(verbose_name='Все места заняты'),
        ),
        migrations.AlterField(
            model_name='daycontent',
            name='13:00',
            field=models.BooleanField(verbose_name='Все места заняты'),
        ),
        migrations.AlterField(
            model_name='daycontent',
            name='13:30',
            field=models.BooleanField(verbose_name='Все места заняты'),
        ),
        migrations.AlterField(
            model_name='daycontent',
            name='14:00',
            field=models.BooleanField(verbose_name='Все места заняты'),
        ),
        migrations.AlterField(
            model_name='daycontent',
            name='14:30',
            field=models.BooleanField(verbose_name='Все места заняты'),
        ),
        migrations.AlterField(
            model_name='daycontent',
            name='15:00',
            field=models.BooleanField(verbose_name='Все места заняты'),
        ),
        migrations.AlterField(
            model_name='daycontent',
            name='15:30',
            field=models.BooleanField(verbose_name='Все места заняты'),
        ),
        migrations.AlterField(
            model_name='daycontent',
            name='16:00',
            field=models.BooleanField(verbose_name='Все места заняты'),
        ),
        migrations.AlterField(
            model_name='daycontent',
            name='16:30',
            field=models.BooleanField(verbose_name='Все места заняты'),
        ),
        migrations.AlterField(
            model_name='daycontent',
            name='17:00',
            field=models.BooleanField(verbose_name='Все места заняты'),
        ),
        migrations.AlterField(
            model_name='daycontent',
            name='17:30',
            field=models.BooleanField(verbose_name='Все места заняты'),
        ),
        migrations.AlterField(
            model_name='daycontent',
            name='18:00',
            field=models.BooleanField(verbose_name='Все места заняты'),
        ),
        migrations.AlterField(
            model_name='daycontent',
            name='18:30',
            field=models.BooleanField(verbose_name='Все места заняты'),
        ),
        migrations.AlterField(
            model_name='daycontent',
            name='19:00',
            field=models.BooleanField(verbose_name='Все места заняты'),
        ),
        migrations.AlterField(
            model_name='daycontent',
            name='19:30',
            field=models.BooleanField(verbose_name='Все места заняты'),
        ),
        migrations.AlterField(
            model_name='daycontent',
            name='20:00',
            field=models.BooleanField(verbose_name='Все места заняты'),
        ),
        migrations.AlterField(
            model_name='daycontent',
            name='20:30',
            field=models.BooleanField(verbose_name='Все места заняты'),
        ),
        migrations.AlterField(
            model_name='daycontent',
            name='21:00',
            field=models.BooleanField(verbose_name='Все места заняты'),
        ),
        migrations.AlterField(
            model_name='daycontent',
            name='21:30',
            field=models.BooleanField(verbose_name='Все места заняты'),
        ),
        migrations.AlterField(
            model_name='daycontent',
            name='22:00',
            field=models.BooleanField(verbose_name='Все места заняты'),
        ),
        migrations.AlterField(
            model_name='daycontent',
            name='22:30',
            field=models.BooleanField(verbose_name='Все места заняты'),
        ),
        migrations.AlterField(
            model_name='daycontent',
            name='23:00',
            field=models.BooleanField(verbose_name='Все места заняты'),
        ),
        migrations.AlterField(
            model_name='daycontent',
            name='23:30',
            field=models.BooleanField(verbose_name='Все места заняты'),
        ),
        migrations.AlterField(
            model_name='days',
            name='date',
            field=models.DateField(default=None, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='days',
            name='day_content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.daycontent', verbose_name='Время'),
        ),
        migrations.AlterField(
            model_name='days',
            name='month',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='administration.reservation', verbose_name='Месяц'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='administration.categorysection', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='photo',
            field=models.FileField(upload_to='', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='price',
            field=models.CharField(max_length=255, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='workday',
            name='end_time',
            field=models.TimeField(default=None, verbose_name='Конец рабочего дня'),
        ),
        migrations.AlterField(
            model_name='workday',
            name='is_vacation',
            field=models.BooleanField(verbose_name='Выходной'),
        ),
        migrations.AlterField(
            model_name='workday',
            name='start_time',
            field=models.TimeField(default=None, verbose_name='Начало рабочего дня'),
        ),
    ]
