# Generated by Django 4.2.6 on 2024-03-02 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0011_order_remove_daycontent_12_00_guests_quantity_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name_plural': 'Заявки на бронирование'},
        ),
        migrations.AlterField(
            model_name='about',
            name='inscription',
            field=models.TextField(default=None, null=True, verbose_name='Подпись'),
        ),
    ]
